import type { QueryClient } from '@tanstack/react-query'
import type { Grade } from '@mynt/core'

import { supabase } from '../lib/supabase'
import { bindersQueryKey } from '../binders/useBinders'
import { collectionQueryKey, type CollectionEntry } from '../collection/useCollection'

/**
 * Every mutation is registered here by key rather than defined inside a hook.
 *
 * That is what makes them survive a reload: a mutation queued offline is
 * persisted as a key plus its variables, and on resume TanStack Query looks the
 * function back up by that key. A mutationFn living in a closure inside a
 * component would be gone by then.
 *
 * Two rules follow, and both are load-bearing:
 *
 *  - Ids are generated by the caller and travel in the variables. Generating
 *    one inside the mutation would hand a retry a different id and duplicate
 *    the row.
 *  - Writes are upserts, so replaying a mutation that in fact reached the
 *    server before the connection dropped is a no-op rather than a duplicate.
 */

export const mutationKeys = {
  addCoin: ['coin', 'add'],
  fileCoin: ['coin', 'file'],
  unfileCoin: ['coin', 'unfile'],
  createBinder: ['binder', 'create'],
  createPage: ['page', 'create'],
} as const

export interface AddCoinVariables {
  id: string
  profileId: string
  coinTypeId: number
  grade: Grade | null
  countryCode: string
  faceValueCents: number
  year: number
}

export interface FileCoinVariables {
  coinId: string
  pageId: string
  row: number
  column: number
}

export interface CreateBinderVariables {
  id: string
  profileId: string
  name: string
}

export interface CreatePageVariables {
  id: string
  binderId: string
  number: number
  rowCount: number
  columnCount: number
}

/** Replaces by id rather than appending, so re-running onMutate is harmless. */
function upsertEntry(client: QueryClient, entry: CollectionEntry) {
  client.setQueryData<CollectionEntry[]>(collectionQueryKey, (current) => [
    ...(current ?? []).filter((e) => e.id !== entry.id),
    entry,
  ])
}

function patchEntry(
  client: QueryClient,
  coinId: string,
  patch: Partial<CollectionEntry>,
) {
  client.setQueryData<CollectionEntry[]>(collectionQueryKey, (current) =>
    (current ?? []).map((e) => (e.id === coinId ? { ...e, ...patch } : e)),
  )
}

export function registerMutations(client: QueryClient) {
  client.setMutationDefaults(mutationKeys.addCoin, {
    mutationFn: async (input: AddCoinVariables) => {
      const { error } = await supabase.from('coin').upsert({
        id: input.id,
        profile_id: input.profileId,
        coin_type_id: input.coinTypeId,
        grade: input.grade,
      })
      if (error) throw error
    },
    onMutate: (input: AddCoinVariables) => {
      upsertEntry(client, {
        id: input.id,
        countryCode: input.countryCode,
        faceValueCents: input.faceValueCents,
        year: input.year,
        variant: '',
        grade: input.grade,
        acquiredOn: null,
        notes: null,
        location: null,
      })
    },
  })

  client.setMutationDefaults(mutationKeys.fileCoin, {
    mutationFn: async (input: FileCoinVariables) => {
      const { error } = await supabase
        .from('coin')
        .update({ page_id: input.pageId, slot_row: input.row, slot_column: input.column })
        .eq('id', input.coinId)
      if (error) throw error
    },
    onMutate: (input: FileCoinVariables) => {
      // The location is rendered from the binder name and page number, which
      // the binders cache already holds -- itself persisted, so this works
      // offline too.
      const binders = client.getQueryData<
        { id: string; name: string; pages: { id: string; number: number }[] }[]
      >(bindersQueryKey)
      const binder = binders?.find((b) => b.pages.some((p) => p.id === input.pageId))
      const page = binder?.pages.find((p) => p.id === input.pageId)
      if (!binder || !page) return
      patchEntry(client, input.coinId, {
        location: {
          pageId: page.id,
          binderId: binder.id,
          binderName: binder.name,
          pageNumber: page.number,
          row: input.row,
          column: input.column,
        },
      })
    },
  })

  client.setMutationDefaults(mutationKeys.unfileCoin, {
    mutationFn: async (coinId: string) => {
      const { error } = await supabase
        .from('coin')
        .update({ page_id: null, slot_row: null, slot_column: null })
        .eq('id', coinId)
      if (error) throw error
    },
    onMutate: (coinId: string) => patchEntry(client, coinId, { location: null }),
  })

  client.setMutationDefaults(mutationKeys.createBinder, {
    mutationFn: async (input: CreateBinderVariables) => {
      const { error } = await supabase
        .from('binder')
        .upsert({ id: input.id, profile_id: input.profileId, name: input.name })
      if (error) throw error
    },
    onSuccess: () => client.invalidateQueries({ queryKey: bindersQueryKey }),
  })

  client.setMutationDefaults(mutationKeys.createPage, {
    mutationFn: async (input: CreatePageVariables) => {
      const { error } = await supabase.from('page').upsert({
        id: input.id,
        binder_id: input.binderId,
        number: input.number,
        row_count: input.rowCount,
        column_count: input.columnCount,
      })
      if (error) throw error
    },
    onSuccess: () => client.invalidateQueries({ queryKey: bindersQueryKey }),
  })
}
